# add table recommend history
"""
Revision ID: bec9447f2f8d
Revises: bf4c657b883b
Create Date: 2025-11-21 03:49:39.347352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec9447f2f8d'
down_revision = 'bf4c657b883b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend_histories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommend_histories_food_id'), 'recommend_histories', ['food_id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_id'), 'recommend_histories', ['id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_user_id'), 'recommend_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommend_histories_user_id'), table_name='recommend_histories')
    op.drop_index(op.f('ix_recommend_histories_id'), table_name='recommend_histories')
    op.drop_index(op.f('ix_recommend_histories_food_id'), table_name='recommend_histories')
    op.drop_table('recommend_histories')
    # ### end Alembic commands ###
