# add table user_food_preferences
"""
Revision ID: bf4c657b883b
Revises: dfe70536cf17
Create Date: 2025-11-21 00:04:39.388481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4c657b883b'
down_revision = 'dfe70536cf17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_food_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('food_id', sa.String(), nullable=False),
    sa.Column('preference_type', sa.Enum('LIKE', 'DISLIKE', 'ALLERGY', name='userfoodpreferencetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_food_preferences_id'), 'user_food_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_food_preferences_id'), table_name='user_food_preferences')
    op.drop_table('user_food_preferences')
    # ### end Alembic commands ###
