# modified table recommend_history
"""
Revision ID: bff586ad48d2
Revises: a9c0788bcb16
Create Date: 2025-12-15 07:17:22.086024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff586ad48d2'
down_revision = 'a9c0788bcb16'
branch_labels = None
depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('recommend_histories', 'user_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('recommend_histories', 'food_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.create_foreign_key(None, 'recommend_histories', 'foods', ['food_id'], ['id'])
#     op.create_foreign_key(None, 'recommend_histories', 'users', ['user_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'recommend_histories', type_='foreignkey')
#     op.drop_constraint(None, 'recommend_histories', type_='foreignkey')
#     op.alter_column('recommend_histories', 'food_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('recommend_histories', 'user_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     # ### end Alembic commands ###

# FIX: For sqlite
def upgrade() -> None:
    # Drop and recreate recommend_histories table with correct types
    op.drop_table('recommend_histories')
    
    op.create_table('recommend_histories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('food_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommend_histories_food_id'), 'recommend_histories', ['food_id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_id'), 'recommend_histories', ['id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_user_id'), 'recommend_histories', ['user_id'], unique=False)


def downgrade() -> None:
    # Recreate with old schema
    op.drop_table('recommend_histories')
    
    op.create_table('recommend_histories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommend_histories_food_id'), 'recommend_histories', ['food_id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_id'), 'recommend_histories', ['id'], unique=False)
    op.create_index(op.f('ix_recommend_histories_user_id'), 'recommend_histories', ['user_id'], unique=False)
